openapi: 3.0.0
info:
  title: E-Commerce API
  version: 1.0.0
  description: API documentation for E-Commerce system
servers:
  - url: 'http://localhost:4000'
    description: Development server

paths:
  /signup:
    $ref: './docs/paths/auth.yaml#/paths/api/auth/signup'
  /login:
    $ref: './docs/paths/auth.yaml#/paths/api/auth/login'
  /category/create:
    $ref: './docs/paths/category.yaml#/paths/api/category/create'

components:
  schemas:
    RegisterUser:
      $ref: './docs/schemas/authSchemas.yaml#/RegisterUser'
    LoginUser:
      $ref: './docs/schemas/authSchemas.yaml#/LoginUser'
    CreateCategory:
      $ref: './docs/schemas/categorySchemas.yaml#/CreateCategory'
